---
- name: Add Docker GPG key
  apt_key: 
    url: "{{ docker_key_url }}"
    state: present

- name: Add Docker official repo
  apt_repository:
    repo: '{{ docker_repo}}'
    state: present
    filename: docker

- name: Install Docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ docker_packages }}"
  notify: enable and restart docker

- name: Install docker python library
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ pip_packages }}"   