---
- name: Create docker directory
  file:
    path: "/home/{{ serveruser }}/docker/gitea"
    state: directory
    owner: "{{ serveruser }}"
    group: "{{ serveruser }}"
    mode: 0755

- name: Create Gitea docker container from inline docker-compose
  community.general.docker_compose:
    project_name: Gitea
    recreate: always
    definition:
      version: '3.3'

      networks:
        gitea:
          external: false

      services:
        sever:
          image: gitea/gitea:latest
          container_name: gitea
          environment:
            - USER_UID=1000
            - USER_GUI=1000
          restart: always
          networks:
            - gitea
          volumes:
            - "/home/{{ serveruser }}/docker/gitea:/data"
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
          ports:
            - "3000:3000"
            - "80:80"
            - "222:22"
            

