---
- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ packages }}"

- name: Create .vnc directory
  file:
    path: "/home/{{ vncuser }}/.vnc"
    state: directory
    mode: 0755
    owner: "{{ vncuser }}"
    group: "{{ vncuser }}"

- name: Copy xtartup file into .vnc directory
  copy:
    src: xstartup
    dest: "/home/{{ vncuser }}/.vnc/xstartup"
    mode: 0755
    owner: "{{ vncuser }}"
    group: "{{ vncuser }}"

- name: Set vnc passwords tightvnc
  shell: |
    set -o pipefail
    echo {{ vncpassword }} | vncpasswd -f > /home/{{ vncuser }}/.vnc/passwd
  args:
    chdir: "/home/{{ vncuser }}/.vnc"
    creates: "/home/{{ vncuser }}/.vnc/passwd"
    executable: /bin/bash

- name: Change ownership and permissions on passwd file
  file:
    path: "/home/{{ vncuser }}/.vnc/passwd"
    owner: "{{ vncuser }}"
    group: "{{ vncuser }}"
    mode: 0700        

- name: Create vncserver systemd service
  template:
    src: vncserver@.service.j2
    dest: /etc/systemd/system/vncserver@.service
    mode: 0644
    owner: root
    group: root
  notify: Enable and start vncserver


     
      
        